export const LOAD_EDUCATIONS = 'LOAD_EDUCATIONS';
export const CREATE_NEW_EDUCATION = 'CREATE_NEW_EDUCATION';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const CREATING_NEW_EDUCATION = 'CREATING_NEW_EDUCATION';
export const LOADING_EDUCATIONS = 'LOADING_EDUCATIONS';
export const LOAD_EDUCATIONS_ERROR = 'LOAD_EDUCATIONS_ERROR';
export const CREATE_NEW_EDUCATION_ERROR = 'CREATE_NEW_EDUCATION_ERROR';